#
# Copyright (c) 2026, Mirocom Laboratories
# All rights reserved.
#
# The following sources are CONFIDENTIAL and PROPRIETARY
# property of Mirocom Laboratories. Unauthorized copying,
# use, distrubution or modification of this file, in whole
# and in part, is strictly prohibited without the prior written
# consent from Mirocom Laboratories.
#

include ../mk/sys.mk

.PHONY: all
all: init

.PHONY: init
init:
	cd init/; $(MAKE) $(PASSDOWN_ARGS)
